version: '3.3'
services:
    db:
      image: mysql:5.7
      volumes:
        - db_data:/var/lib/mysql
        - ./mysql-dump:/docker-entrypoint-initdb.d
      restart: always
      environment:
        MYSQL_DATABASE: 'challenge'
        MYSQL_USER: 'challenge'
        MYSQL_PASSWORD: 'challenge'
        MYSQL_ROOT_PASSWORD: 'challenge'
      ports:
        - '3306'
      command: --default-authentication-plugin=mysql_native_password

    node:
      image: "node:10"
      depends_on: 
        - db
      restart: always
      working_dir: /home/node/app
      environment:
        - NODE_ENV=production
        - DB_NAME=challenge
        - DB_TEST=challenge_test
        - DB_USER=challenge
        - DB_PASS=challenge
        - DB_HOST=db
        - DB_PORT=3306
        - API_PORT=8080
        - CMP_TOKEN=70bee172-3f5e-475f-9e21-2a84b37ee17b
        - CMP_URL=https://sandbox-api.coinmarketcap.com
        - CRON=*/5 * * * *
      volumes:
        - ./:/home/node/app
      expose:
        - "8080"
      ports: 
        - 8080:8080
      command: >
        bash -c "./node_modules/.bin/sequelize db:migrate &&
                 ./node_modules/.bin/sequelize db:seed:all &&
                  npm start"

volumes:
  db_data: {}
